### PR TITLE
auto-recover from error

### LINKED ISSUE #232: franka_control_node incorrectly handles controller starting
1. Trying to start a `ros_control` controller when the robot is not in automatic mode (external activation device pushed down), `franka_control_node` correctly rejects the operation: 
`[ERROR] [ros.franka_control]: libfranka: Move command rejected: command not possible in the current mode!`
But: the controller is reported as started, e.g. in rqt's controller manager plugin.
2. If the robot is switched back to automatic mode (external activation device pulled up), starting a controller is still not possible:
    - `franka_control_node` doesn't report an error (anymore)
    - the controller is reported to be active in rqt, but the controller isn't actually running!
3. To enable starting a controller, one needs to re-launch `franka_control_node`, which is rather annoying if it is part of a larger roslaunch file.

### PR DESCRIPTION
**Pull request by rhaschke**
This implements auto-recovering from errors when the user-stop button is pressed+unpressed and thus the robot's mode switches to idle. Without that, one has to trigger the `error_recovery` action.
Partially fixes #232

### CODE REVIEW

**Comment by Ekanshh** [comment]
@rhaschke I faced this issue today, and it took me a lot of time to figure out this issue. Thanks for mentioning it and creating a PR. I hope they merge it asap.

File: franka_control/src/franka_control_node.cpp [hunk 1]
```diff
@@ -124,6 +124,11 @@ int main(int argc, char** argv) {
           control_manager.update(now, now - last_time);
           franka_control.checkJointLimits();
           last_time = now;
+
+          if (has_error && franka_control.robotMode() == franka::RobotMode::kIdle) {
+            franka_control.robot().automaticErrorRecovery();
```
Comment (andrejpan) [inline franka_control/src/franka_control_node.cpp]: This line is unnecessary. We will remove it and merge this PR.

Please let us know if we are missing something.

Edit: This will be merged latest first week of 2023.

Comment (rhaschke) [reply franka_control/src/franka_control_node.cpp]: Which line exactly do you refer to? As you already force-pushed, I cannot easily see my suggested code anymore.
But in a different place, you call `automaticErrorRecovery()` as well:
https://github.com/frankaemika/franka_ros/blob/c392c9112e1184f6dad5437f4453cb8020de4219/franka_control/src/franka_control_node.cpp#L53-L54
Why is it unnecessary here?

Comment (Maverobot) [reply franka_control/src/franka_control_node.cpp]: We meant the line ` robot.automaticErrorRecovery(); `. In the `if` condition, being in `franka::RobotMode::kIdle` mode already means that no error is present. Therefore, the ` robot.automaticErrorRecovery();` is unnecessary. 

At that different place, if the mode is `franka::RobotMode::kIdle`, then `robot.automaticErrorRecovery();` would also be unnecessary. We just always call it there for simplicity.

@rhaschke By the way, do you think merging this PR is enough for closing the issue https://github.com/frankaemika/franka_ros/issues/232 ?

**Review by marcbone — APPROVED** [review]

**Review by Maverobot — APPROVED** [review]
